# Backends
upstream gitea_backend {
    server 127.0.0.1:8081;
}

upstream bluesky_backend {
    server 127.0.0.1:8082;
}

upstream roundcube_backend {
    server 127.0.0.1:8083;
}

upstream website_backend {
    server unix:/run/website/app.sock;
}

# Plaintext
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name nercone.dev       *.nercone.dev
                nerc1.dev         *.nerc1.dev
                diamondgotcat.net *.diamondgotcat.net
                d-g-c.net         *.d-g-c.net;

    return 301 https://$host$request_uri;
}

# Gitea (SSL/TLS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name git.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/error.conf;

    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    location / {
        proxy_pass http://gitea_backend;
        include /etc/nginx/snippets/proxy.conf;
    }
}

# Bluesky PDS (SSL/TLS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name pds.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;

    client_max_body_size    300m;
    proxy_request_buffering off;

    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

    location / {
        proxy_pass http://bluesky_backend;
        include /etc/nginx/snippets/proxy.conf;
    }
}

# Roundcube (SSL/TLS)
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name mx.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/error.conf;

    root  /var/www/roundcube/public_html;
    index index.php;

    client_max_body_size 50m;

    location ~ ^/(config|temp|logs|vendor|bin|SQL)/ {
        return 404;
    }

    location ~ /\. {
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include /etc/nginx/snippets/fastcgi.conf;
        fastcgi_pass roundcube_backend;
    }
}

# MTA-STS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;

    server_name mta-sts.nercone.dev;

    include /etc/nginx/snippets/tls-http.conf;

    location = /.well-known/mta-sts.txt {
        default_type text/plain;
        add_header Cache-Control "max-age=2592000";
        return 200 "version: STSv1\r\nmode: enforce\r\nmx: mx.nercone.dev\r\nmax_age: 2592000\r\n";
    }

    location / {
        return 404;
    }
}

# SSL/TLS
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    http2 on;

    server_name nercone.dev       *.nercone.dev
                nerc1.dev         *.nerc1.dev
                diamondgotcat.net *.diamondgotcat.net
                d-g-c.net         *.d-g-c.net;

    include /etc/nginx/snippets/tls-http.conf;
    include /etc/nginx/snippets/error.conf;

    proxy_read_timeout 300s;
    proxy_send_timeout 300s;

    location ~* \.(ttf|otf|woff|woff2)$ {
        proxy_pass http://website_backend;
        proxy_buffering off;
        include /etc/nginx/snippets/proxy.conf;
    }

    location / {
        proxy_pass http://website_backend;
        include /etc/nginx/snippets/proxy.conf;
    }
}
