include /etc/nginx/snippets/error.conf;

root  /var/www/roundcube/public_html;
index index.php;

client_max_body_size 50m;

location ~ ^/(config|temp|logs|vendor|bin|SQL)/ {
    return 404;
}

location ~ /\. {
    return 404;
}

location = /favicon.ico {
    rewrite ^ /static.php/skins/elastic/images/favicon.ico last;
}

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

location ~ ^.+\.php(/.*)?$ {
    fastcgi_split_path_info ^(.+\.php)(/.*)$;

    try_files $fastcgi_script_name =404;

    include /etc/nginx/snippets/fastcgi.conf;
    fastcgi_pass roundcube_backend;
}
