ssl_protocols TLSv1.2 TLSv1.3;

ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305;
ssl_conf_command Ciphersuites TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256;
ssl_ecdh_curve X25519MLKEM768:SecP384r1MLKEM1024:SecP256r1MLKEM768:MLKEM1024:MLKEM768:X25519:prime256v1:secp384r1;
ssl_prefer_server_ciphers on;

ssl_conf_command SignatureAlgorithms ecdsa_secp384r1_sha384;

ssl_certificate     /etc/letsencrypt/live/nercone.dev/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/nercone.dev/privkey.pem;
ssl_certificate_compression on;

ssl_ech_file /etc/nginx/ech/ech.nerc1.dev.pem;

ssl_session_cache shared:SSL:10m;
ssl_session_timeout 4h;
ssl_session_tickets off;

ssl_early_data off;

ssl_stapling off;
ssl_stapling_verify off;

add_header Alt-Svc 'h3=":443"; ma=86400';
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
